mdapiconvert/LightningFlow/objects/Action_Plan_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Problem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action Plan Problem</label>
        <referenceTo>Action_Plan_Problem__c</referenceTo>
        <relationshipLabel>Action Plan Goals</relationshipLabel>
        <relationshipName>Action_Plan_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>GoalTemplate__c</fullName>
        <label>GoalTemplate</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Action Plan Goal</label>
    <nameField>
        <label>Action Plan Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiconvert/LightningFlow/objects/Action_Plan_Problem__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action Plan Template</label>
        <referenceTo>Action_Plan_Template__c</referenceTo>
        <relationshipLabel>Action Plan Problems</relationshipLabel>
        <relationshipName>Action_Plan_Problems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Action Plan Problems</relationshipLabel>
        <relationshipName>Action_Plan_Problems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProblemTemplate__c</fullName>
        <label>Problem Template</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Action Plan Problem</label>
    <nameField>
        <label>Action Plan Problem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiconvert/LightningFlow/objects/Action_Plan_Template__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Action Plan Template</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiconvert/LightningFlow/classes/CreateActionPlan.cls
public class CreateActionPlan {

    @InvocableMethod(label='Create action Plan' description='Create action Plans')
    public static List<String> createActionPlan(List<actionPlanInfo> actionPlans)
    {
        //Add validation that all data is present.
		Action_Plan_Template__c actionPlanTemplate = new Action_Plan_Template__c();
		List<Action_Plan_Template__c> actionPlanTemplates = new List<Action_Plan_Template__c>();
		List<Action_Plan_Problem__c> templateProblems = new List<Action_Plan_Problem__c>();
        List<Action_Plan_Goal__c> templateGoals  = new List<Action_Plan_Goal__c>();

		List<String> templateProblemIds = new List<String>();
        List<String> templateGoalIds = new List<String>();
        ActionPlanInfo actionPlan = new ActionPlanInfo();
        if (!actionPlans.isEmpty()) {
            actionPlan = actionPlans[0];
        }
        system.debug('actionPlan $$ ' + actionPlan);
		
        //Get Template
        if(actionPlan.templateId != null)
        {
            actionPlanTemplates = [select id, Name, description__c from Action_Plan_Template__c where id =:actionPlan.templateId  and active__c = true limit 1];
            if (!actionPlanTemplates.isEmpty())
            {
                actionPlanTemplate = actionPlanTemplates[0];
            }
        }
        system.debug('actionPlanTemplate $$ ' + actionPlanTemplate);
        //Get template Problems, based on problems
        templateProblems = [select id, name, Action_Plan_Template__c, Description__c, Priority__c, Sort_Order__c
                           from Action_Plan_Problem__c where Action_Plan_Template__c = :actionPlanTemplate.id ];
        system.debug('templateProblems $$ ' + templateProblems);
        
        //Loop through and get problemIds
        for (Action_Plan_Problem__c p : templateProblems)
        {
            templateProblemIds.add(p.id);
        }
        system.debug('templateProblemIds ' + templateProblemIds);
        //Get Template goals based on problems
        if (!templateProblemIds.isEmpty())
        {
            templateGoals = [select id, name, Description__c, Priority__c, Action_Plan_Problem__c, Sort_Order__c	
                             from Action_Plan_Goal__c where Action_Plan_Problem__c in :templateProblemIds];
        }
                 
        //Create action plan (Case)
        Case newactionPlan = new Case();
        newactionPlan.contactId = actionPlan.contactId;
        newactionPlan.Subject = actionPlanTemplate.name;
        newactionPlan.Status = 'New';
        newActionPlan.Description = actionPlanTemplate.Description__c;
        newactionPlan.Priority = 'Medium';
        
        insert newactionPlan;
        
        system.debug('newactionPlan $$ ' + newactionPlan);
        //Create action Plan Problems. 
        List<Action_Plan_Problem__c> actionPlanProblems = new List<Action_Plan_Problem__c>();
        for (Action_Plan_Problem__c p : templateProblems)
        {
            Action_Plan_Problem__c newactionPlanProblem = new Action_Plan_Problem__c();
            newActionPlanProblem.Case__c = newactionPlan.id;
           // newActionPlanProblem.Action_Plan_Template__c = actionPlanTemplate.id;
            newActionPlanProblem.ProblemTemplate__c =  p.id;
            newActionPlanProblem.Description__c = p.Description__c;
            newActionPlanProblem.Priority__c = p.Priority__c;
            newActionPlanProblem.Sort_Order__c = p.Sort_Order__c;
            newactionPlanProblem.Name = p.name;
            actionPlanProblems.add(newActionPlanProblem);
        }
        insert actionPlanProblems;
        
        system.debug('actionPlanProblems $$ ' + actionPlanProblems);
        //Create action Plan Goals. 
        List<Action_Plan_Goal__c> actionPlanGoals = new List<Action_Plan_Goal__c>();
        for (Action_Plan_Goal__c  g : templateGoals)
        {
            Action_Plan_Goal__c newactionPlanGoal = new Action_Plan_Goal__c();
            //newactionPlanGoal.Action_Plan_Problem__c = newactionPlan.id;
            for (Action_Plan_Problem__c p : actionPlanProblems)
            {
                if (g.Action_Plan_Problem__c == p.ProblemTemplate__c )
                {
                    newactionPlanGoal.Action_Plan_Problem__c = p.id;
                    newactionPlanGoal.GoalTemplate__c = g.id;
                }
            }
           // newactionPlanGoal.Action_Plan_Problem__c = newactionPlan.id;
           // newactionPlanGoal.HealthCloudGA__actionPlanTemplate__c = actionPlanTemplate.id;
            newactionPlanGoal.Priority__c = g.Priority__c;
            newactionPlanGoal.name = g.name;
            newactionPlanGoal.Description__c = g.Description__c;
            newactionPlanGoal.Sort_Order__c = g.Sort_Order__c;
            actionPlanGoals.add(newactionPlanGoal);
        }
        insert actionPlanGoals;
		system.debug('actionPlanGoals $$ ' + actionPlanGoals);
        
        return new List<String>{newactionPlan.id};
    }
    
    


public class ActionPlanInfo {
		@invocableVariable
        public  String templateId;
  		@invocableVariable
        public  String contactId;
    	@invocableVariable
        public  Integer score;

}
}