force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <label>Action_Plan_Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In work</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapiconvert/LightningFlow/objects/Action_Plan_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Problem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action Plan Problem</label>
        <referenceTo>Action_Plan_Problem__c</referenceTo>
        <relationshipLabel>Action Plan Goals</relationshipLabel>
        <relationshipName>Action_Plan_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Action Plan Goal</label>
    <nameField>
        <label>Action Plan Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan_Goal__c/fields/Action_Plan_Template_Goal__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template_Goal__c</fullName>
    <label>Action Plan Template Goal</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

mdapiconvert/LightningFlow/objects/Action_Plan_Problem__c.object
<CustomObject>
    <fields>
        <fullName>Action_Plan_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action Plan Template</label>
        <referenceTo>Action_Plan_Template__c</referenceTo>
        <relationshipLabel>Action Plan Problems</relationshipLabel>
        <relationshipName>Action_Plan_Problems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Action Plan Problems</relationshipLabel>
        <relationshipName>Action_Plan_Problems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Action Plan Problem</label>
    <nameField>
        <label>Action Plan Problem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan_Problem__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan__c</fullName>
    <label>Action Plan</label>
    <referenceTo>Action_Plan__c</referenceTo>
    <relationshipLabel>Action Plan Problems</relationshipLabel>
    <relationshipName>Action_Plan_Problems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Action_Plan_Problem__c/fields/Action_Plan_Template_Problem__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template_Problem__c</fullName>
    <label>Action Plan Template Problem</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

mdapiconvert/LightningFlow/objects/Action_Plan_Template__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Action Plan Template</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan_Template_Goal__c/Action_Plan_Template_Goal__c.object-meta.xml
<CustomObject>
    <label>Action Plan Template Goal</label>
    <nameField>
        <label>Action Plan Goal Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Template Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan_Template_Goal__c/fields/Action_Plan_Template_Problem__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template_Problem__c</fullName>
    <label>Action Plan Template Problem</label>
    <referenceTo>Action_Plan_Template_Problem__c</referenceTo>
    <relationshipLabel>Action Plan Template Goals</relationshipLabel>
    <relationshipName>Action_Plan_Template_Goals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Action_Plan_Template_Problem__c/Action_Plan_Template_Problem__c.object-meta.xml
<CustomObject>
    <label>Action Plan Template Problem</label>
    <nameField>
        <label>Action Plan Template Problem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Template Problems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan_Template_Problem__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <label>Action Plan Template</label>
    <referenceTo>Action_Plan_Template__c</referenceTo>
    <relationshipLabel>Action Plan Template Problems</relationshipLabel>
    <relationshipName>Action_Plan_Template_Problems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CreateActionPlan.cls
public class CreateActionPlan {

    /* createActionPlan
     * Bulkified for Multiple records
     */
    @InvocableMethod(label='Create Action Plan' description='Create Action Plans')
    public static List<String> createActionPlan(List<actionPlanInfo> actionPlanInfos)
    {
        //Add validation that all data is present.
		Action_Plan_Template__c actionPlanTemplate = new Action_Plan_Template__c();
		List<Action_Plan_Template__c> actionPlanTemplates = new List<Action_Plan_Template__c>();
		List<Action_Plan_Template_Problem__c> templateProblems = new List<Action_Plan_Template_Problem__c>();
        List<Action_Plan_Template_Goal__c> templateGoals  = new List<Action_Plan_Template_Goal__c>();

		List<String> templateProblemIds = new List<String>();
        List<String> templateGoalIds = new List<String>();

        //ActionPlanInfo actionPlan = new ActionPlanInfo();
        /*if (!actionPlans.isEmpty()) {
            actionPlan = actionPlans[0];
        }*/
        List<String> actionPlanTemplateIds = new List<String>();
        for (ActionPlanInfo api : actionPlanInfos)
        {
            actionPlanTemplateIds.add(api.templateId);
        }

        system.debug('actionPlan $$ ' + actionPlanInfos);
		
        //Get Template
        if(!actionPlanTemplateIds.isEmpty())
        {
            actionPlanTemplates = [select id, Name, description__c from Action_Plan_Template__c where id in:actionPlanTemplateIds  and active__c = true limit 500];
        }
        system.debug('actionPlanTemplate $$ ' + actionPlanTemplate);
        //Get template Problems, based on problems
        templateProblems = [select id, name, Action_Plan_Template__c, Description__c, Priority__c, Sort_Order__c
                           from Action_Plan_Template_Problem__c where Action_Plan_Template__c in :actionPlanTemplates ];
        system.debug('templateProblems $$ ' + templateProblems);
        
        //Loop through and get problemIds
        for (Action_Plan_Template_Problem__c p : templateProblems)
        {
            templateProblemIds.add(p.id);
        }
        system.debug('templateProblemIds ' + templateProblemIds);
        //Get Template goals based on problems
        if (!templateProblemIds.isEmpty())
        {
            templateGoals = [select id, name, Description__c, Priority__c, Action_Plan_Template_Problem__c, Sort_Order__c	
                             from Action_Plan_Template_Goal__c where Action_Plan_Template_Problem__c in :templateProblemIds];
        }
        List<Action_Plan__c> actionPlans = new List<Action_Plan__c>();
        for (Action_Plan_Template__c apt : actionPlanTemplates)
        {

        
            for (ActionPlanInfo ap : actionPlanInfos)
            {
                //Create action plan
                if (ap.templateId == apt.id)
                {
                    Action_Plan__c newactionPlan = new Action_Plan__c();
                    newactionPlan.Contact__c = ap.contactId;
                    newactionPlan.Name = apt.name;
                    newactionPlan.Status__c = 'New';
                    newActionPlan.Description__c = apt.Description__c;
                    newActionPlan.Action_Plan_Template__c = apt.id;
                    //Associate action plan to case when case is passed to it
                    newActionPlan.Case__c = ap.caseId;
                    actionPlans.add(newActionPlan);
                    break;
                }

            }
        }
        insert actionPlans;
        
        system.debug('actionPlans $$ ' + actionPlans);
        //Create action Plan Problems. 
        List<Action_Plan_Problem__c> actionPlanProblems = new List<Action_Plan_Problem__c>();
        for (Action_Plan_Template_Problem__c p : templateProblems)
        {       
                for (Action_Plan__c ap : actionPlans)
                {
                    //Need to match on template Id and action plan to create problem
                    system.debug('action plan template $$ ' + p.Action_Plan_Template__c + ' ' + ap.Action_Plan_Template__c);
                    if (p.Action_Plan_Template__c == ap.Action_Plan_Template__c)
                    {
                        Action_Plan_Problem__c newactionPlanProblem = new Action_Plan_Problem__c();
                        newActionPlanProblem.Description__c = p.Description__c;
                        newActionPlanProblem.Priority__c = p.Priority__c;
                        newActionPlanProblem.Sort_Order__c = p.Sort_Order__c;
                        newactionPlanProblem.Name = p.name;
                        newactionPlanProblem.Action_Plan_Template_Problem__c = p.id;
                        newActionPlanProblem.Action_Plan__c = ap.id;
                        actionPlanProblems.add(newActionPlanProblem);
                        break;
                    }
                }
                
        }
        insert actionPlanProblems;
        
        system.debug('actionPlanProblems $$ ' + actionPlanProblems);
        //Create action Plan Goals. 
        List<Action_Plan_Goal__c> actionPlanGoals = new List<Action_Plan_Goal__c>();
        for (Action_Plan_Template_Goal__c  g : templateGoals)
        {
           
            //newactionPlanGoal.Action_Plan_Problem__c = newactionPlan.id;
            for (Action_Plan_Problem__c pp : actionPlanProblems)
            {
                system.debug('action plan problem $$ ' + pp.Action_Plan_Template_Problem__c + ' ' + 
                    pp.Action_Plan_Template_Problem__c);
                if (g.Action_Plan_Template_Problem__c == pp.Action_Plan_Template_Problem__c )
                {
                    Action_Plan_Goal__c newactionPlanGoal = new Action_Plan_Goal__c();
                    newactionPlanGoal.Action_Plan_Problem__c = pp.id;
                    newactionPlanGoal.Priority__c = g.Priority__c;
                    newactionPlanGoal.name = g.name;
                    newactionPlanGoal.Description__c = g.Description__c;
                    newactionPlanGoal.Sort_Order__c = g.Sort_Order__c;
                    newactionPlanGoal.Action_Plan_Template_Goal__c = g.id;
                    actionPlanGoals.add(newactionPlanGoal);
                    break;
                }
            }
            
        }
        insert actionPlanGoals;
		system.debug('actionPlanGoals $$ ' + actionPlanGoals);
        
        List<String> returnIds = new List<String>();
        for (Action_Plan__c ap : actionPlans)
        {
            returnIds.add(ap.id);
        }
        return returnIds;
    }
    
    


public class ActionPlanInfo {
		@invocableVariable
        public  String templateId;
  		@invocableVariable
        public  String contactId;
    	@invocableVariable
        public  String caseId;

}
}