force-app/main/default/objects/Action_Plan__c/Action_Plan__c.object-meta.xml
<CustomObject>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <label>Action_Plan_Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiconvert/LightningFlow/objects/Action_Plan_Template__c.object
<CustomObject>
    <label>Action Plan Template</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateActionPlanTest.cls
@isTest
public class CreateActionPlanTest {
    

    static testmethod void test1() {
        CreateActionPlanTestData.intialize();
        Test.startTest();
        List<Action_Plan_Template__c> templates = [select id, Name From Action_Plan_Template__c Where name = 'High Risk Plan' limit 1];
        List<Contact> theContact = [select id, name from Contact limit 1];
        List<Case> theCase = [select id from Case limit 1];
        List<CreateActionPlan.ActionPlanInfo> infos = new List<CreateActionPlan.ActionPlanInfo>();
        CreateActionPlan.ActionPlanInfo newAPI = new CreateActionPlan.ActionPlanInfo();
        newAPI.contactId = theContact[0].id;
        newAPI.templateId = templates[0].id;
        newAPI.caseId = theCase[0].id;
        infos.add(newAPI);
        CreateActionPlan.createActionPlan(new List<CreateActionPlan.ActionPlanInfo>{newAPI});
        List<Action_Plan__c> actionPlans = new List<Action_Plan__c>();
        actionPlans = [select id, Name from Action_Plan__c where Contact__c = :theContact[0].id ];
        system.assertEquals(actionPlans.size(), 1);
        Test.stopTest();
    }
}